import Head from  'next/head'
import Header from './header'
import dynamic from 'next/dynamic'
import { useEffect, useState } from 'react'
import { Waveform } from '@uiball/loaders'

export default function MobileLayout({ children }: Props) {
  const [isHydrated, setIsHydrated] = useState(false);

  useEffect(() => {
    setIsHydrated(true);
  }, []);
  
  // wait for hydration
  // TODO: auth check
  if (!isHydrated) {
    return (
      <>
        <Head>
          <title>Musix</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <div className="flex items-center justify-center h-full w-full">
          <Waveform
            size={40}
            lineWeight={2}
            speed={1}
            color="black"
          />
        </div>
      </>
    )
  }
  
  return (
    <>
      <Head>
        <title>Musix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <div className="flex flex-col h-full">
        <Header />
        <DynamicToaster />
        <main className="grow py-6 px-4">
          {children}
        </main>
      </div>
    </>
  )
}

// ------------------------------ //
// dynamic imports

const DynamicToaster = dynamic(
  () => import("./toaster"), { ssr: false }
);

// ------------------------------ //
// types

type Props = {
  children: React.ReactNode;
}