import useMusixStore from '@/shared/store';
import { Waveform } from '@uiball/loaders'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { useRouter } from 'next/router';

export default function Login({ code }: { code: string }) {
  const { setUser } = useMusixStore();
  const router = useRouter();

  useEffect(() => {
    // fetch user data from backend using code
    fetch(`http://127.0.0.1:8000/auth/login`, {
      method: 'POST',
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ code: code }),
    })
      .then(res => res.json())
      .then(data => {
        setUser(data);
      })
      .catch(err => console.error(err));
  }, []);

  return (
    <>
      <Head>
        <title>Musix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="flex items-center justify-center h-full w-full">
        <Waveform
          size={40}
          lineWeight={2}
          speed={1}
          color="black"
        />
      </div>
    </>
  )
}

export const getServerSideProps: GetServerSideProps<{ code: string }> = async (context) => {
  // get query params
  const { code } = context.query;

  return {
    props: {
      code: code as string,
    },
  };
}